apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: g6vzs4a5e-python-gitops
  description: This is GitOps manifest for g6vzs4a5e-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=g6vzs4a5e-python
    backstage.io/kubernetes-id: g6vzs4a5e-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: g6vzs4a5e-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:g6vzs4a5e-python
