apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: g6vzs4a5e-python
  janus-idp.io/tekton: g6vzs4a5e-python
  backstage.io/kubernetes-id: g6vzs4a5e-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: g6vzs4a5e-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
